dependencies:
  - python
  - scikit-learn
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - pyyaml
  - yaml
  - python-duckdb
  - python-dotenv
  - pytest
  - pip
  - pip:
    - geneticalgorithm

